[dev]
  command = "npm run start"
  framework = "#custom"
  targetPort = 8080
  port = 8888

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "jsonwebtoken", "cookie", "zod", "jose"]
  included_files = ["netlify/lib/**"]

[build]
  publish = "_site"
  functions = "netlify/functions"
